### ISSUE TITLE
What's the dataset split for different strategies?

### ISSUE THREAD

**Issue by YY-GX** [j96w/cogail#2]
Hi, could you kindly share how the provided datasets are split according to different strategies?

For instance, for the 2D-Fetch-Quest task, there're 4 strategies. And the provided dataset (dataset-continuous-info-act) has 200 files. I wonder about the file index range for these 4 strategies.

Thanks for helping!

**Comment by j96w** [comment]
For the 2DFetchQuest, the first 100 files (0-99) are a mix of strategy-1 and 2, 100-149 is strategy-3, 150-200 is strategy-4.

The data split is defined in the training and evaluation data loaders. For the 2D-FetchQuest task, the training data split could be found in `cogail/libs/datasets/dataset_exp1.py` line 9. The evaluation data split could be found in `cogail/scripts/eval_replay.py` line 128. They are loading different trajectory indexes in the dataset as the training and testing set.

**Comment by YY-GX** [comment]
Thans a lot! Could you also show how files split by strategies for HR-Handover and HR-SeqManip?
