### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by YY-GX** [j96w/cogail#3]
After training, how can I visualize the results using Pygame or IGibson?

**Comment by j96w** [comment]
If you want to turn on the visualization of each task, you simply just need to switch the `render-mode` in the `cogail/configs/exp1_config.py` from `headless` to `gui`. Exp2 and Exp3 are the same. Basically, it will turn on the visualization in `cogail/libe/envs/env_exp1.py` line 236.

**Comment by YY-GX** [comment]
Thank you!
