### ISSUE TITLE
Meshes for the Humanoid experiments

### ISSUE THREAD

**Issue by prasuchit** [j96w/cogail#4]
Hi,

I don't see any meshes folder for the URDF files placed in iGibson/igibson/data/assets/models.

For instance, fetch.urdf line 11 has meshes/base_link.obj. But there is no such folder.

Where can I get them? Or did I miss something in the instructions?

Kindly help.

**Comment by j96w** [comment]
Hi, sorry for the late update. I just uploaded all the model assets to [this folder](https://drive.google.com/drive/folders/1ZdQz3QQGLJusz-mMTUB29XjQbEtcF_Uk?usp=sharing). Feel free to download and try again with the code. Thanks!
