### ISSUE TITLE
Missing mesh for humanoid_hri

### ISSUE THREAD

**Issue by yuchenmo** [j96w/cogail#5]
Hi, when I run the two iGibson experiments (cogail_exp2_handover and cogail_exp3_seqmanip), I got such error messages:
`<path_to_iGibson>/iGibson/igibson/data/assets/models/humanoid_hri/humanoid_hri_knee.urdf:676: cannot find 'l_finger_collision.obj' in any directory in urdf path`

It seems the meshes for the humanoid are not included in this repo. Could you please upload them or tell us how/where can we get these models? Thanks!

**Comment by j96w** [comment]
Hi, sorry for the late update. Please check [this folder](https://drive.google.com/drive/folders/1ZdQz3QQGLJusz-mMTUB29XjQbEtcF_Uk?usp=sharing) to download the l_finger_collision.obj.
